name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
permissions:
  contents: write
  issues: write
jobs:
  check-bats-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g bats
      - run: npm install
      - run: bats -v
      - run: echo "Hello" >> "1.txt"
      - run: git add .
      - run: git commit -m 'Adding a new File in the repo'
      - run: git push origin master
      - run: npm run build